language: ruby
bundler_args: "--jobs=2"
script:
- bundle-audit check --update
- bundle exec rails db:setup
- bundle exec rspec
- bundle exec rubocop
services:
- postgresql
env:
  global:
  - secure: e0FyM4KtUjqICUM9lO7lgCxc8kLX1HCyptlzgsVR2ir5udOp7uPYfyHMfy4DhWCTcJNiMX53a3RRR2r03mHPJdWlT3E0XiphJdDdLxyUvs6MCSnk3pG83VFwuuYjkwBriVK1BHxhYD2pWbggb+kHkwggyEByqlYE5QFjZ1g9JnbEXyOHNzhtcOCKlsm4BN6nCGeqy6CCnLvmCf817/31oWtuCJuajpfHjRKzY+vhK9+idZo4e2vDTs2q8x/ovXUAfZiPM7rYwWZYyETN141FTS6shY3fnii3e0E3WpfskGVAzXWHq92fBXffDHsM6Xyy0oyCJwRm3j99Z1TWAQY5iHWBeu+qaNONIJVgjB0xepgoFgdOFiCkzfGIeVTlOJDrDqWQP1TWc9JpnlUcLefMO2OnRHdgD3UEKg7h54X8iNvZ2nJSivfKyZ3AZ4HKbKBH6Y6CW1Fu1yGG40xHBOtwNoaxhoxX0fCu1M1QowljqOlclB44WvG52PuOCLnORYL9Iu2hLFoWDFKTkXoPej5e9NalOh4NDTQfxYNfHHfHHUoYKPsGf2gLgTPTcwVKnW7wX2jI0RyTP2z4jsXa9Ataw7oqCbeImhhfmyN7ZbaOYsmzQH9LEo9VWhlLaMj1sGMjyIN1xztuecOgm8QIHBnhMBVT3su3Wza8ZH+ZhcRQdPc=
  - secure: C7DImcnjXyCgjGpGkW900zdPTB993QjQQvkfMnijikVxdPEeOO13my63TQypGbI9vN1wbcLdGEcanxcQcbuHh0Ch2Kr8vsQEIJjPOh3d6H/8XtlXcMJtcLULTDDIf1XvBBcVYspCebmXCODy/I9bQiZICvQ5lyTod3RuczUXcyr9XplpRoRPSbQR3lv4dR2gDJj5SUff7W8X74hHe8DFNGYY5qMBHwXmb6UfkGJDKmInlsYyXCL9BSep85e7ge+vgvtU3jVImMU40smGjn3bUsmyoDSDZbaKvE0KFJeSHfltxl/Y44hsC/JGEyBT+EycJCXoVNvDzHzJ9bpL3pCPUPC+2n4EPRO1zQD0YmDq0rhOyo0D/zKTKj5i54pvZPvrnRpDJw52sG98KPz035naXg22AoHViJ28vmRJq7o7VE5VABe0kRdL0SmquGzi1lWnEAa3F+JbbQ7k10v/2uCjFgd3ngK45Ui3dKqOnhj8jEqQNprIhBWg/55LaasHKlXzvYhcAPY0GVaKWuKETZcwer6E1OM+sb36oHju6oQANj3MJWCWpWyn7f5QFjvCHgq5XNxX9AmhnVwgeX9xplMUyU3aIaz3uBJS70CnHKHck8mzlq9mMnYCUXMDDUvcKvsx5AnLcKR1/kqCWv0VmTyhC4OTCw8i2rmxBxJCjccDQts=
